import { Product } from '../types/product';

export interface MockProduct extends Product {
  imagenLocal: any;
}

export const mockProducts: MockProduct[] = [
  {
    id: 1,
    nombre: 'Nintendo Switch 2 + Mario Kart',
    precio: 2800000,
    marca: 'Nintendo',
    caracteristicas_basicas: 'Plataforma: Consola híbrida\nAlmacenamiento: 256GB\nPantalla: 7" LCD',
    caracteristicas_tecnicas: 'Conectividad: WiFi 6, Bluetooth 5.0\nBatería: 5220 mAh',
    imagen: null,
    imagenLocal: require('../assets/images/ac_switch2_mariokart.jpg'),
    stock: 10,
    subcategoria_id: 1,
  },
  {
    id: 2,
    nombre: 'ASUS Vivobook 16',
    precio: 3549900,
    marca: 'ASUS',
    caracteristicas_basicas: 'Sistema Operativo: Windows 11\nProcesador: Intel Core i5\nMemoria RAM: 16GB',
    caracteristicas_tecnicas: 'Almacenamiento: 512GB SSD\nPantalla: 16" FHD\nTarjeta Gráfica: Intel Iris',
    imagen: null,
    imagenLocal: require('../assets/images/ap_asusvivobook16.jpg'),
    stock: 5,
    subcategoria_id: 2,
  },
  {
    id: 3,
    nombre: 'Insta360 Ace Pro 2',
    precio: 1679726,
    marca: 'Insta360',
    caracteristicas_basicas: 'Resolución: 8K\nEstabilización: FlowState\nAlmacenamiento: 64GB',
    caracteristicas_tecnicas: 'Batería: 1650 mAh\nConectividad: WiFi, Bluetooth\nPantalla: LCD',
    imagen: null,
    imagenLocal: require('../assets/images/ac_insta360.jpg'),
    stock: 8,
    subcategoria_id: 3,
  },
  {
    id: 4,
    nombre: 'Motorola Edge 50 Fusion',
    precio: 999900,
    marca: 'Motorola',
    caracteristicas_basicas: 'Sistema Operativo: Android 14\nProcesador: Snapdragon 7s Gen 2\nMemoria RAM: 8GB',
    caracteristicas_tecnicas: 'Almacenamiento: 256GB\nPantalla: 6.7" pOLED 144Hz\nBatería: 5000 mAh',
    imagen: null,
    imagenLocal: require('../assets/images/am_motorola_edge50fusion.jpg'),
    stock: 15,
    subcategoria_id: 4,
  },
  {
    id: 5,
    nombre: 'ASUS Intel Core i9',
    precio: 3469900,
    marca: 'ASUS',
    caracteristicas_basicas: 'Sistema Operativo: Windows 11\nProcesador: Intel Core i9\nMemoria RAM: 32GB',
    caracteristicas_tecnicas: 'Almacenamiento: 1TB SSD\nPantalla: 16" FHD\nTarjeta Gráfica: RTX 4060',
    imagen: null,
    imagenLocal: require('../assets/images/ap_asus_corei9.jpg'),
    stock: 3,
    subcategoria_id: 2,
  },
  {
    id: 6,
    nombre: 'MSI Katana 17.3',
    precio: 9999200,
    marca: 'MSI',
    caracteristicas_basicas: 'Sistema Operativo: Windows 11\nProcesador: Intel Core i7\nMemoria RAM: 16GB',
    caracteristicas_tecnicas: 'Almacenamiento: 1TB SSD\nPantalla: 17.3" FHD 144Hz\nTarjeta Gráfica: RTX 4070',
    imagen: null,
    imagenLocal: require('../assets/images/ap_katana17.jpg'),
    stock: 4,
    subcategoria_id: 2,
  },
  {
    id: 7,
    nombre: 'Combo Kalley Teclado',
    precio: 199900,
    marca: 'Kalley',
    caracteristicas_basicas: 'Tipo: Teclado + Mouse\nConectividad: USB\nColor: Negro',
    caracteristicas_tecnicas: 'Compatibilidad: Universal\nCable: 1.5m\nBotones: 3',
    imagen: null,
    imagenLocal: require('../assets/images/apg_combo4.jpg'),
    stock: 20,
    subcategoria_id: 6,
  },
  {
    id: 8,
    nombre: 'PS5 Digital 1TB Slim',
    precio: 2599000,
    marca: 'PlayStation',
    caracteristicas_basicas: 'Plataforma: Consola de sobremesa\nAlmacenamiento: 1TB SSD\nResolución: 4K',
    caracteristicas_tecnicas: 'Conectividad: WiFi 6, Bluetooth 5.1\nProcesador: AMD Zen 2\nBatería: N/A',
    imagen: null,
    imagenLocal: require('../assets/images/ac_ps5_digital1tb.jpg'),
    stock: 6,
    subcategoria_id: 1,
  },
  {
    id: 9,
    nombre: 'Lenovo AIO',
    precio: 3599000,
    marca: 'Lenovo',
    caracteristicas_basicas: 'Sistema Operativo: Windows 11\nProcesador: Intel Core i3\nMemoria RAM: 8GB',
    caracteristicas_tecnicas: 'Almacenamiento: 512GB SSD\nPantalla: 21.5" FHD\nTarjeta Gráfica: Intel UHD',
    imagen: null,
    imagenLocal: require('../assets/images/ae_lenovo_aio.jpg'),
    stock: 7,
    subcategoria_id: 7,
  },
];